[package]
name = "vtenc"
edition.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"

[lib]
bench = false

[dependencies]
atoi_simd = "0.16.1"
constcat = "0.6.1"
itoa = "1.0"

[dev-dependencies]
bytes = "1.0"
