[package]
name = "vtmsg"
edition.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"

[lib]
bench = false

[dependencies]
vtenc = { path = "../vtenc" }

[dev-dependencies]
vtinput = { path = "../vtinput" }
bytes = "1.0"
