[package]
name = "vtio_control_base"
edition.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"

[dependencies]
derive_more.workspace = true
smallvec = { version = "1.15.0", features = ["const_new", "const_generics"] }
vtenc = { path = "../vtenc" }
