[package]
name = "vtio_control_derive_internal"
edition.workspace = true
license.workspace = true
authors.workspace = true
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro2-diagnostics = "0.10"
quote = "1"
syn = { version = "2", features = ["full"] }
